packages:
  - apps/*
  - packages/*

catalog:
  react: ^19
  react-dom: ^19
  typescript: ^5.7.2
  turbo: ^2.3.3
  eslint: ^9.17.0
  "eslint-config-prettier": ^9.1.0
  "eslint-plugin-prettier": ^5.2.1
  "eslint-plugin-import": ^2.31.0
  "eslint-plugin-json": ^4.0.1
  "eslint-plugin-react": ^7.37.3
  "eslint-plugin-react-hooks": ^5.1.0
  "eslint-plugin-tailwindcss": ^3.17.5
  "@eslint/js": ^9.17.0
  "@eslint/json": ^0.9.0
  "typescript-eslint": ^8.18.2
  "prettier": ^3.4.2
  "@types/react": ^19.0.2
  "@types/react-dom": ^19.0.2
  "storybook": ^8.4.7
  "@storybook/addon-essentials": ^8.4.7
  "@storybook/addon-interactions": ^8.4.7
  "@storybook/addon-onboarding": ^8.4.7
  "@storybook/blocks": ^8.4.7
  "@storybook/nextjs": ^8.4.7
  "@storybook/react": ^8.4.7
  "@storybook/test": ^8.4.7
